name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]  # Use '14.x' instead of specific patch version

    steps:
    - uses: actions/setup-node@v2  # Use setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build --if-present

    - name: Test
      run: npm test
